### PR TITLE
Proposed solution to issue #8

### PR DESCRIPTION
**Pull request by kvting**
This is my proposed solution to issue #8 (In ios 7 if i try to push a ViewController from your code it doesn't pass the Navigationbar but in iOS 6 it does.).

I only add a completion block to `- (void)dismissAnimated:(BOOL)animated`

We normally show the sidebar on our navigation controller:

```
RNFrostedSidebar *callout = [[RNFrostedSidebar alloc] initWithImages:images];
    callout.delegate = self;
    [callout show];
```

Then dismiss it using `- (void)dismissAnimated:(BOOL)animated completion:(void (^)(BOOL status))finish;`:

```
- (void)sidebar:(RNFrostedSidebar *)sidebar didTapItemAtIndex:(NSUInteger)index {
    [sidebar dismissAnimated:YES completion:^(BOOL status) {
        if (status) {
            [self.navigationController pushViewController:myNewVC animated:YES];
        }
    }];
}
```

The advantage compare to the previous proposed solution is that you doesn't need to hide the navigation bar while the sidebar is shown.

### CODE REVIEW

**Comment by rnystrom** [comment]
I like where you're going, but why basically rewrite [<code>-dismissAnimated:</code>](https://github.com/rnystrom/RNFrostedSidebar/blob/master/RNFrostedSidebar.m#L478-512)?

**Comment by kvting** [comment]
@rnystrom There's no specific reason, just thought that I didn't want modify the original code... I'll change it later when I have a bit of time.

**Comment by rnystrom** [comment]
Couple things, and I'll merge this:

### Completion Handler

Instead of an [empty completion handler](https://github.com/kvting/RNFrostedSidebar/blob/master/RNFrostedSidebar.m#L383-384), just call dismiss like this:

``` objc
[rn_frostedMenu dismissAnimated:NO completion:nil]
```

This happens [here](https://github.com/kvting/RNFrostedSidebar/blob/master/RNFrostedSidebar.m#L383-384) and [here](https://github.com/kvting/RNFrostedSidebar/blob/master/RNFrostedSidebar.m#L517-518).

### Naming Conventions

Also, please change the parameters and variables [here](https://github.com/kvting/RNFrostedSidebar/blob/master/RNFrostedSidebar.h#L77) to look like:

``` objc
- (void)dismissAnimated:(BOOL)animated completion:(void (^)(BOOL finished))completion;
```

### Example Project

I'm not sure what is going on [here](https://github.com/kvting/RNFrostedSidebar/blob/master/example/ViewController.m#L65-67). Could you clean up the formatting?

### Graceful Degradation

You've removed the [<code>-dismiss</code> and <code>-dismissAnimated:</code>](https://github.com/rnystrom/RNFrostedSidebar/blob/master/RNFrostedSidebar.h#L77-78) methods from the original project. What would happen if people updated their projects with this new feature? 

They would all break.

You need to restore those two methods so that they call your new method like so

``` objc
- (void)dismiss {
    [self dismissAnimated:YES completion:nil];
}

- (void) dismissAnimated:(BOOL)animated {
    [self dismissAnimated:animated completion:nil];
}
```

### Readme

I think your solution solves a good problem. It would be great to add a bit in the [Usage](https://github.com/rnystrom/RNFrostedSidebar#usage) section in the Readme on how to use RNFrostedSidebar with a UINavigationController.

**Comment by kvting** [comment]
First sorry for the mess... I've should had done it properly and not botch it.
Thanks for your detail criticism and advices.

**Comment by kvting** [comment]
Done. Concerning the Readme, hope it will satisfy you as English isn't my first language.

**Comment by jithinpala** [comment]
in iOS 7 it showing an error method "animateWithDuration:delay:usingSpringWithDamping:initialSpringVelocity:options:animations:completion:" not found..
Please help me to solve this

**Comment by rnystrom** [comment]
@kvting Incredible job. Thanks so much for your contribution!

**Comment by kvting** [comment]
@rnystrom Thanks and happy to help

**Pull request merged**
